routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/set-language/{lang}', 'LanguagesController@set')->name('set.language');
Route::get('/', 'HomeController@index')->name('home');
// Route::get('/estates/{property_type}', 'EstatesController@index')->name('estates');


Route::post('/search', 'SearchController@index')->name('searchwith');
Route::get('/search', 'SearchController@index')->name('search');
Route::get('/flats', 'FlatController@index')->name('flats');
Route::get('/villas', 'VillaController@index')->name('villas');
Route::get('/lands', 'LandController@index')->name('lands');
Route::get('/landsrff', 'LandRffController@index')->name('landsrff');
Route::get('/farms', 'FarmController@index')->name('farms');
Route::get('/projects', 'ProjectController@index')->name('projects');
Route::get('/details/{listing_uid}', 'DetailsController@index')->name('details');



Route::get('provinces/get/', 'UtilityController@getProvinces');
Route::get('districts/get/{id}', 'UtilityController@getDistricts');

Auth::routes();

Route::resource('/techsupport', 'TechSupportController');
Route::get('/adminhome', 'AdminHomeController@index')->name('adminhome');
Route::get('/settings', 'SettingsController@index')->name('settings');
Route::resource('/listings', 'ListingsController');
Route::post('/precreate', 'ListingsController@create')->name('precreate');

Route::get('/downloadpresentation/{uid}', 'ListingsController@download_presentation')->name('download_presentation');
Route::get('/deletepresentation/{uid}', 'ListingsController@delete_presentation')->name('delete_presentation');

Route::post('/imgupload', 'ImageController@upload')->name('image_upload');
Route::post('/getimages', 'ImageController@get_images')->name('get_images');
Route::post('/deleteimage', 'ImageController@delete_image')->name('delete_image');

app/Listing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Listing extends Model
{

    protected $fillable = ['presentation'];

    public function images() {
        return $this->hasMany('App\ListingImage' , 'listing_uid','unique_id');
    }

    public function property_type()
    {
        return $this->belongsTo('App\PropertyType');
    }

    public function listing_type()
    {
        return $this->hasOne('App\ListingType' , 'id', 'listing_type_id');
    }

    public function province()
    {
        return $this->belongsTo('App\Province');
    }

    public function district()
    {
        return $this->belongsTo('App\District');
    }

    public function currency()
    {
        return $this->belongsTo('App\Currency');
    }

    public function heating_type()
    {
        return $this->belongsTo('App\HeatingType');
    }

    public function deed_type()
    {
        return $this->belongsTo('App\DeedType');
    }

    public function swimming_pool()
    {
        return $this->belongsTo('App\SwimmingPool');
    }
    public function zoning()
    {
        return $this->belongsTo('App\Zoning');
    }

    public function flat()
    {
        return $this->belongsTo('App\Flat', 'unique_id', 'unique_id');
    }

    public function land()
    {
        return $this->belongsTo('App\Land','unique_id', 'unique_id');
    }

    public function farm()
    {
        return $this->belongsTo('App\Farm','unique_id', 'unique_id');
    }

    public function villa()
    {
        return $this->belongsTo('App\Villa','unique_id', 'unique_id');
    }

    public function project()
    {
        return $this->belongsTo('App\Project','unique_id', 'unique_id');
    }

    public function farm_type()
    {
        return $this->belongsTo('App\FarmType');
    }

    public function farm_subject()
    {
        return $this->belongsTo('App\FarmSubject');
    }

}

app/ListingType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ListingType extends Model
{
    //
}

app/Http/Controllers/ListingsController.php
<?php

namespace App\Http\Controllers;

use App\Currency;
use App\DeedType;
use App\District;
use App\Farm;
use App\FarmSubject;
use App\FarmType;
use App\Flat;
use App\HeatingType;
use App\Land;
use App\Listing;
use App\ListingImage;
use App\ListingType;
use App\Presentation;
use App\Project;
use App\PropertyType;
use App\Province;
use App\Villa;
use App\Zoning;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class ListingsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $property_types = PropertyType::all();
        $listing_types = ListingType::all();
        // $currencies = Currency::all();
        $flats = Listing::with(['images', 'property_type', 'listing_type', 'province', 'district', 'currency', 'flat', 'farm', 'land'])->get();

        $listings = $flats;

        //$listings = Listing::with(['property_type', 'listing_type', 'province', 'district'])->get();

        // echo "<pre>"; print_r($listings);
        return view('listings.index',
            [
                'listings' => $listings,
                'property_types' => $property_types,
                'listing_types' => $listing_types,
            ]);

    }

    public function create(Request $request)
    {
        $unique_id = uniqid();
        $provinces = Province::all(); // Getting all provinces
        $deed_types = DeedType::all(); // Getting all provinces
        $districts = District::where('province_id', 40)->get(); // Checking Istanbul Districts
        $property_type = PropertyType::find($request->property_type);
        $listing_type = ListingType::find($request->listing_type);
        $currencies = Currency::all();
        $heating_types = HeatingType::all();
        $zonings = Zoning::all();
        $farm_types = FarmType::all();
        $farm_subjects = FarmSubject::all();


        return view(
            'listings.create',
            [
                'edit' => false,
                'unique_id' => $unique_id,
                'provinces' => $provinces,
                'districts' => $districts,
                'currencies' => $currencies,
                'deed_types' => $deed_types,
                'zonings' => $zonings,
                'farm_types' => $farm_types,
                'farm_subjects' => $farm_subjects,
                'heating_types' => $heating_types,
                'property_type' => $property_type,
                'listing_type' => $listing_type,
            ]);

    }

    public function store(Request $request)

    {
        $this->validate($request, [
            'title' => 'required',
            'presentation' => 'mimes:pdf|nullable|max:10000'
        ]);

        // Handle Presentation Upload

        if ($request->hasFile('presentation')) {
            $path = $request->file('presentation')->store('presentations');
        }

        $listing = new Listing;
        $listing->unique_id = $request->unique_id;
        $listing->title = $request->title;
        $listing->property_type_id = $request->property_type;
        $listing->listing_type_id = $request->listing_type;
        $listing->province_id = $request->province;
        $listing->district_id = $request->district;
        $listing->price = $request->price;
        $listing->currency_id = $request->currency;
        $listing->details = $request->details;
        $listing->precedent_value = $request->precedent_value;


        if ($request->hasFile('presentation')) {
            $listing->presentation = $request->file('presentation')->hashName();
        }
        $listing->save();

        switch ($request->property_type) {
            case 1:

                $estate = new Flat;
                $estate->unique_id = $request->unique_id;
                $estate->gross_area = $request->gross_area;
                $estate->net_area = $request->net_area;
                $estate->room = $request->room;
                $estate->saloon = $request->saloon;
                $estate->bath = $request->bath;
                $estate->building_age = $request->building_age;
                $estate->flats_floor = $request->flats_floor;
                $estate->building_floor_count = $request->building_floor_count;
                $estate->balcony = ($request->balcony) ? 1 : 0;
                $estate->furnished = ($request->furnished) ? 1 : 0;
                $estate->heating_type_id = $request->heating_type;
                $estate->deed_type_id = $request->deed_type;
                $estate->save();

                break;

            case 2:

                $land = new Land;
                $land->unique_id = $request->unique_id;
                $land->rff = 0;
                $land->gross_area = $request->gross_area;
                $land->net_area = $request->net_area;
                $land->block = $request->block;
                $land->plot = $request->plot;
                $land->zoning_id = $request->zoning;
                $land->save();

                break;

            case 3:

                $land = new Land;
                $land->unique_id = $request->unique_id;
                $land->rff = 1;
                $land->gross_area = $request->gross_area;
                $land->net_area = $request->net_area;
                $land->block = $request->block;
                $land->plot = $request->plot;
                $land->zoning_id = $request->zoning;
                $land->total_construction_area = $request->total_construction_area;
                $land->rff_rate = $request->rff_rate;
                $land->apprx_cost = $request->apprx_cost;
                $land->apprx_gain = $request->apprx_gain;
                $land->apprx_timetofinish = $request->apprx_timetofinish;
                $land->kaks = $request->kaks;
                $land->taks = $request->taks;

                $land->save();

                break;

            case 4:
                // TODO: Change variable name to a generic type

                $farm = new Farm;
                $farm->unique_id = $request->unique_id;
                $farm->net_area = $request->net_area;
                $farm->closed_area = $request->closed_area;
                $farm->block = $request->block;
                $farm->plot = $request->plot;
                $farm->farm_type_id = $request->farm_type;
                $farm->farm_subject_id = $request->farm_subject;
                $farm->is_active = ($request->is_active) ? 1 : 0;
                $farm->animal_count = $request->animal_count;
                $farm->save();

                break;

            case 5:

                $estate = new Villa;
                $estate->unique_id = $request->unique_id;
                $estate->gross_area = $request->gross_area;
                $estate->net_area = $request->net_area;
                $estate->room = $request->room;
                $estate->saloon = $request->saloon;
                $estate->bath = $request->bath;
                $estate->building_age = $request->building_age;
                $estate->floor_count = $request->floor_count;
                $estate->balcony = ($request->balcony) ? 1 : 0;
                $estate->furnished = ($request->furnished) ? 1 : 0;
                $estate->security = $request->security;
                $estate->swimming_pool_id = $request->swimming_pool;
                $estate->playground = $request->playground;
                $estate->sportsarea = $request->sportsarea;
                $estate->walkingpath = $request->walkingpath;
                $estate->parking = $request->parking;
                $estate->heating_type_id = $request->heating_type;
                $estate->deed_type_id = $request->deed_type;
                $estate->save();

                break;

            case 6:

                $estate = new Project;
                $estate->unique_id = $request->unique_id;
                $estate->gross_area = $request->gross_area;
                $estate->net_area = $request->net_area;
                $estate->room = $request->room;
                $estate->saloon = $request->saloon;
                $estate->bath = $request->bath;
                $estate->building_age = $request->building_age;
                $estate->floor_count = $request->floor_count;
                $estate->balcony = ($request->balcony) ? 1 : 0;
                $estate->furnished = ($request->furnished) ? 1 : 0;
                $estate->security = $request->security;
                $estate->swimming_pool_id = $request->swimming_pool;
                $estate->playground = $request->playground;
                $estate->sportsarea = $request->sportsarea;
                $estate->walkingpath = $request->walkingpath;
                $estate->parking = $request->parking;
                $estate->heating_type_id = $request->heating_type;
                $estate->deed_type_id = $request->deed_type;
                $estate->save();

                break;

        }

        return redirect('listings');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $listing = Listing::where('id', $id)->get();
        $provinces = Province::all(); // Getting all provinces
        $districts = District::all(); // Getting all districts
        $deed_types = DeedType::all();
        $currencies = Currency::all();
        $heating_types = HeatingType::all();
        $zonings = Zoning::all();
        $farm_types = FarmType::all();
        $farm_subjects = FarmSubject::all();


        return view(
            'listings.edit',
            [
                'edit' => true,
                'listing' => $listing[0],
                'provinces' => $provinces,
                'districts' => $districts,
                'currencies' => $currencies,
                'heating_types' => $heating_types,
                'zonings' => $zonings,
                'deed_types' => $deed_types,

resources/views/listings/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>{{ __($listing_type->name) }} {{ __($property_type->name) }} Ekle # {{ $unique_id }}</h4>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>

                    <div class="panel-body">
                        <div class="col-sm-4">
                            {{-- IMAGE SECTION --}}
                            @include('listings.images')

                        </div>

                        <form id="listing_form" method="POST" action="{{ route('listings.store') }}"
                              enctype="multipart/form-data">

                            {{ csrf_field() }}
                            {{-- PREDEFINED OR HIDDEN INPUTS --}}

                            <input type="hidden" name="unique_id" value="{{ $unique_id }}">
                            <input type="hidden" name="listing_type" value="{{ $listing_type->id }}">
                            <input type="hidden" name="property_type" value="{{ $property_type->id }}">
                            <div class="col-sm-8">
                                <div class="col-sm-12">
                                    <div class="panel panel-info">
                                        <div class="panel-heading ">
                                            <label>Genel Bilgiler</label>
                                        </div>

                                        <div class="panel-body">

                                            {{-- Listing Title --}}

                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    <div class="input-group">
                                                        <span class="input-group-addon"> İlan Başlığı</span>
                                                        <input id="title" class="form-control"
                                                               placeholder="İlan Başlığı Giriniz"
                                                               name="title"/>

                                                    </div>
                                                </div>
                                            </div>

                                            {{-- Listing Address --}}

                                            <div class="col-sm-5">
                                                <label>Adres</label>
                                                <div class="form-group">
                                                    <div class="input-group">
                                                        <span class="input-group-addon" id="">İl</span>
                                                        <select name="province" class="form-control">
                                                            @foreach($provinces as $province)
                                                                <option value="{{ $province->id }}"
                                                                        @if($province->id == 40) selected @endif>
                                                                    {{ $province->name }}
                                                                </option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group">

                                                    <div class="input-group">
                                                        <span class="input-group-addon" id="">İlçe</span>
                                                        <select name="district" class="form-control">
                                                            @foreach($districts as $district)
                                                                <option value="{{ $district->id }}"
                                                                        @if($district->id == 456) selected @endif>
                                                                    {{ $district->name }}
                                                                </option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>

                                            {{-- Listing Location --}}

                                            <div class="col-sm-2">
                                                <div class="form-group">
                                                    <label for="">Konum</label>
                                                    <div class="input-group">
                                                        <div class="btn btn-light btn-info" data-toggle="modal"
                                                             data-target="#mapModal">
                                                            <i class="fas fa-map-marker-alt"></i>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            {{-- Listing Price --}}

                                            <div class="col-sm-5">
                                                <div class="form-group">
                                                    <label for="">Gayrimenkul Fiyatı</label>
                                                    <div class="input-group">
                                                        <input type="number" min="1" id="title" class="form-control"
                                                               placeholder="Fiyat Girin" name="price"
                                                               style=" height:36px; width:65%">
                                                        <select name="currency" class="input-group-addon"
                                                                style=" height:36px; width:35%">
                                                            @foreach($currencies as $currency)
                                                                <option value="{{ $currency->id }}">{{ $currency->symbol }} {{ $currency->code }}</option>
                                                            @endforeach

                                                        </select>
                                                    </div>
                                                </div>
                                                
                                                <div class="form-group">
                                                    <label for="equal">Emsal Değeri</label>
                                                    <input type="number" id="title" class="form-control"
                                                           name="precedent_value">
                                                </div>
                                            </div>

                                        </div>

                                        <div class="panel-footer">
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <p id="filename">İlanın ayrıntılı bilgilerini içeren sunumu
                                                        ekleyin</p>
                                                </div>
                                                <div class="col-sm-6">
                                                    <input type="file" name="presentation" id="file"/>
                                                    <label class="btn btn-xs btn-success pull-right" for="file">
                                                        Sunum Dosyası Ekle
                                                    </label>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>


                                {{-- Listing Type Dedicated Details --}}

                                @include('listings.listingspecial.pt'.$listing_type->id.'_'.$property_type->id)

                            </div>


                            <div class="col-sm-12 ">

                                <button type="reset" class="btn btn-danger">
                                    <i class="fas fa-times"></i> İptal
                                </button>

                                <button type="submit" id="save_listing" class="btn btn-primary pull-right">
                                    <i class="fas fa-check"></i> Ekle
                                </button>

                            </div>


                        </form>
                    </div>


                </div>
            </div>
        </div>
    </div>
    @include('listings.location')
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(document).ready(function () {
            $('select[name="province"]').on('change', function () {
                var provinceId = $(this).val();
                if (provinceId) {
                    $.ajax({
                        url: '/districts/get/' + provinceId,
                        type: "GET",
                        dataType: "json",
                        success: function (data) {

                            $('select[name="district"]').empty();

                            $.each(data, function (key, value) {

                                $('select[name="district"]').append('<option value="' + key + '">' + value + '</option>');

                            });
                        },

                    });
                } else {
                    $('select[name="district"]').empty();
                }

            });

        });

    </script>
    <script>


        Dropzone.autoDiscover = false;

        let idrop = new Dropzone("#imgDropzone", {
            url: "{{ route('image_upload') }}",
            maxFilesize: "5",
            //addRemoveLinks: true,
            previewsContainer: '#preview',
            previewTemplate: document
                .querySelector('#tpl')
                .innerHTML,
            autoProcessQueue: false,
            uploadMultiple: true,
            parallelUploads: 15,

            success: function () {
                $.ajax({
                    type: "POST",
                    url: "{{ route('get_images') }}",
                    data: {
                        uid: " {{ $unique_id }} "
                    },

                    contentType: "text/json; charset=utf-8",
                    dataType: "text",
                    success: function (msg) {

                    }
                });
            },


            sending: function (file, xhr, formData) {
                formData.append("_token", "{{ csrf_token() }}");
                formData.append("listing_uid", "{{ $unique_id }}");
                formData.append("target", "listing");
            },

            completemultiple: function () {
                $('#listing_form').submit();
                console.log("Images Uploaded")
            }
        });


        idrop.on("addedfile", function (file) {

            file.previewElement.addEventListener("click", (e) => {
                let target = $(e.target);
                console.log(target);
                if (target.is('#remove')) {
                    idrop.removeFile(file);
                }


            })
        });

        $('#save_listing').on('click', function () {
            event.preventDefault();

            if(idrop.getAcceptedFiles().length > 0) {
                showLoading();
                idrop.processQueue();
                console.log("Images Uploading")
            } else {
                alert("En az bir resim eklemeniz gerekiyor");
            }

        })

    </script>

    {{-- Presentation File Form Element --}}
    <script>
        const file_element = $('#file');
        $('#file').on('change', () => {

            if(file_element[0].files.length > 0) {

                $('#filename').html(' <i class="fas fa-file-pdf"></i> ' + file_element[0].files[0].name)
            } else {

                $('#filename').html('İlanın ayrıntılı bilgilerini içeren sunumu ekleyin')

            }
        })
    </script>

@endsection

resources/views/listings/images.blade.php
<div class="row">

    <div id="imgDropzone"
         class="thumbnail text-center"
         style="">
        <i class="fas fa-5x fa-image"></i><br>Resimleri sürükleyin ya da tıklayıp yükleyin.
    </div>
    <div class="panel panel-warning">
        <div class="panel-heading">Resimler</div>
        <div id="preview" class="panel-body">

        </div>
    </div>

</div>


<div class="hidden" id="tpl">
    <div align="center">
        <div class="col-sm-6 dz-preview dz-file-preview thumbnail" style="margin-bottom:5px;">
                <img class="img-responsive" data-dz-thumbnail/>
                <div class="btn-group" style="position: absolute; bottom: 10px; right: 10px">
                    {{-- <button id="main_image" class="btn btn-xs btn-success">
                        <i class="fas fa-home"></i>
                    </button> --}}
                    <button id="remove_image" class="btn btn-xs btn-danger dz-remove" data-dz-remove>
                        <i class="fas fa-trash"></i>
                    </button>
                </div>

            <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress></span>
            </div>
            <div class="dz-error-message"><span data-dz-errormessage></span></div>
        </div>


    </div>

</div>

resources/views/listings/location.blade.php
<div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="mapModalTitle">Gayrimenkulün Konumunu Belirleyin</h5>
            </div>

            <div class="modal-body">
                <div id="map" style="height: 500px; width: 100%;"></div>
            </div>
        </div>
    </div>
</div>

resources/views/listings/picktype.blade.php
<div class="modal fade" id="picktype" tabindex="-1" role="dialog" aria-labelledby="picktypeTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method="POST" action="{{ route('precreate') }}">

                {{ csrf_field() }}

                <div class="modal-header">
                    <h3 class="modal-title" id="picktypeTitle">
                        Yeni Gayrimenkul İlanı
                    </h3>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <input type="hidden" name="listing_type" value="1">
                        <div class="col-sm-4 col-sm-offset-4">
                            <div class="form-group">
                                <label for="property_type">Gayrimenkul Tipi :</label>
                                <select name="property_type" id="property_type" class="form-control">
                                    @foreach($property_types as $property_type)
                                        <option value="{{ $property_type->id }}">{{ __($property_type->name) }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
                    <button type="submit" class="btn btn-primary">Devam Et</button>
                </div>

            </form>
        </div>
    </div>
</div>

<script>

</script>