routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/set-language/{lang}', 'LanguagesController@set')->name('set.language');
Route::get('/', 'HomeController@index')->name('home');
// Route::get('/estates/{property_type}', 'EstatesController@index')->name('estates');


Route::post('/search', 'SearchController@index')->name('searchwith');
Route::get('/search', 'SearchController@index')->name('search');
Route::get('/flats', 'FlatController@index')->name('flats');
Route::get('/villas', 'VillaController@index')->name('villas');
Route::get('/lands', 'LandController@index')->name('lands');
Route::get('/landsrff', 'LandRffController@index')->name('landsrff');
Route::get('/farms', 'FarmController@index')->name('farms');
Route::get('/projects', 'ProjectController@index')->name('projects');
Route::get('/details/{listing_uid}', 'DetailsController@index')->name('details');



Route::get('provinces/get/', 'UtilityController@getProvinces');
Route::get('districts/get/{id}', 'UtilityController@getDistricts');

Auth::routes();

Route::resource('/techsupport', 'TechSupportController');
Route::get('/adminhome', 'AdminHomeController@index')->name('adminhome');
Route::get('/settings', 'SettingsController@index')->name('settings');
Route::resource('/listings', 'ListingsController');
Route::post('/precreate', 'ListingsController@create')->name('precreate');

Route::get('/downloadpresentation/{uid}', 'ListingsController@download_presentation')->name('download_presentation');
Route::get('/deletepresentation/{uid}', 'ListingsController@delete_presentation')->name('delete_presentation');

Route::post('/imgupload', 'ImageController@upload')->name('image_upload');
Route::post('/getimages', 'ImageController@get_images')->name('get_images');
Route::post('/deleteimage', 'ImageController@delete_image')->name('delete_image');

app/Http/Controllers/TechSupportController.php
<?php

namespace App\Http\Controllers;

use App\TechSupportIssue;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TechSupportController extends Controller
{

    public function __construct()
    {

        $this->middleware('auth');

    }

    public function index()
    {
        $issues = TechSupportIssue::where('owner' , Auth::user()->id)->orderBy('created_at','DESC')->get();

//        echo "<pre>";print_r($issues); die();
        return view('techsupport.index' , ['issues' => $issues]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('techsupport.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'subject' => 'required',
            'detail' => 'required'
        ]);

        $issue = new TechSupportIssue();
        $issue->owner = Auth::user()->id;
        $issue->subject = $request->subject;
        $issue->detail = $request->detail;
        $issue->save();

        return redirect(route('techsupport.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/techsupport/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-sm-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Destek İste ya da Görüş Bildir</h3>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

            </div>

            <div class="panel-body">
                <form id="issue_form" method="POST" action="{{ route('techsupport.store') }}"
                      enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="subject">Yardım Konusu :</label>
                        <input class="form-control" name="subject">
                    </div>
                    <div class="form-group">
                        <label for="subject">Detaylar :</label>
                        <textarea class="form-control" name="detail"></textarea>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Gönder</button>
                    </div>

                </form>
            </div>
        </div>

    </div>

@endsection

resources/views/techsupport/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-sm-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                    <h3>Destek ve Görüş İstekleriniz</h3>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <h3 class="pull-right">
                    <a href="{{route('techsupport.create')}}"
                       class="btn btn-xs btn-primary pull-right">
                        Yeni
                    </a>
                </h3>
            </div>
            <div class="panel-body">
                @if(count($issues) != 0)
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Konu</th>
                        <th class="text-right" style="width: 10%">Durum</th>
                        <th class="text-right" style="width: 20%">Bildirim Zamanı</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($issues as $issue)
                    <tr>
                        <td>{{ $issue->subject }}</td>
                        <td class="text-right"> {{ $issue->status->name }}</td>
                        <td class="text-right"> {{ $issue->created_at }}</td>

                    </tr>
                    </tbody>
                    @endforeach
                </table>
                    @else
                    <p>Kayıt bulunamadı</p>
                    @endif
            </div>
        </div>

    </div>

@endsection