routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/set-language/{lang}', 'LanguagesController@set')->name('set.language');
Route::get('/', 'HomeController@index')->name('home');
// Route::get('/estates/{property_type}', 'EstatesController@index')->name('estates');


Route::post('/search', 'SearchController@index')->name('searchwith');
Route::get('/search', 'SearchController@index')->name('search');
Route::get('/flats', 'FlatController@index')->name('flats');
Route::get('/villas', 'VillaController@index')->name('villas');
Route::get('/lands', 'LandController@index')->name('lands');
Route::get('/landsrff', 'LandRffController@index')->name('landsrff');
Route::get('/farms', 'FarmController@index')->name('farms');
Route::get('/projects', 'ProjectController@index')->name('projects');
Route::get('/details/{listing_uid}', 'DetailsController@index')->name('details');



Route::get('provinces/get/', 'UtilityController@getProvinces');
Route::get('districts/get/{id}', 'UtilityController@getDistricts');

Auth::routes();

Route::resource('/techsupport', 'TechSupportController');
Route::get('/adminhome', 'AdminHomeController@index')->name('adminhome');
Route::get('/settings', 'SettingsController@index')->name('settings');
Route::resource('/listings', 'ListingsController');
Route::post('/precreate', 'ListingsController@create')->name('precreate');

Route::get('/downloadpresentation/{uid}', 'ListingsController@download_presentation')->name('download_presentation');
Route::get('/deletepresentation/{uid}', 'ListingsController@delete_presentation')->name('delete_presentation');

Route::post('/imgupload', 'ImageController@upload')->name('image_upload');
Route::post('/getimages', 'ImageController@get_images')->name('get_images');
Route::post('/deleteimage', 'ImageController@delete_image')->name('delete_image');

app/Currency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    //
}

app/DeedType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DeedType extends Model
{
    //
}

app/District.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class District extends Model
{
    public function district()
    {
        return $this->belongsTo('App\Province');
    }
}

app/Farm.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Farm extends Model
{

    public function zoning()
    {
        return $this->hasOne('App\Zoning','id','zoning_id');
    }

    public function farm_type()
    {
        return $this->hasOne('App\FarmType', 'id','farm_type_id');
    }

    public function farm_subject()
    {
        return $this->hasOne('App\FarmSubject', 'id','farm_subject_id');
    }
}

app/FarmSubject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FarmSubject extends Model
{
    //
}

app/FarmType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FarmType extends Model
{
    //
}

app/Flat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Flat extends Model
{

    public function province()
    {
        return $this->belongsTo('App\Province');
    }

    public function district()
    {
        return $this->belongsTo('App\District');
    }

    public function heating_type()
    {
        return $this->hasOne('App\HeatingType', 'id','heating_type_id');
    }

    public function deed_type()
    {
        return $this->belongsTo('App\DeedType');
    }
}

app/HeatingType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HeatingType extends Model
{
    //
}

app/IssueStatus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class IssueStatus extends Model
{
    //
}

app/Land.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Land extends Model
{


    public function zoning()
    {
        return $this->hasOne('App\Zoning','id','zoning_id');
    }

}

app/Listing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Listing extends Model
{

    protected $fillable = ['presentation'];

    public function images() {
        return $this->hasMany('App\ListingImage' , 'listing_uid','unique_id');
    }

    public function property_type()
    {
        return $this->belongsTo('App\PropertyType');
    }

    public function listing_type()
    {
        return $this->hasOne('App\ListingType' , 'id', 'listing_type_id');
    }

    public function province()
    {
        return $this->belongsTo('App\Province');
    }

    public function district()
    {
        return $this->belongsTo('App\District');
    }

    public function currency()
    {
        return $this->belongsTo('App\Currency');
    }

    public function heating_type()
    {
        return $this->belongsTo('App\HeatingType');
    }

    public function deed_type()
    {
        return $this->belongsTo('App\DeedType');
    }

    public function swimming_pool()
    {
        return $this->belongsTo('App\SwimmingPool');
    }
    public function zoning()
    {
        return $this->belongsTo('App\Zoning');
    }

    public function flat()
    {
        return $this->belongsTo('App\Flat', 'unique_id', 'unique_id');
    }

    public function land()
    {
        return $this->belongsTo('App\Land','unique_id', 'unique_id');
    }

    public function farm()
    {
        return $this->belongsTo('App\Farm','unique_id', 'unique_id');
    }

    public function villa()
    {
        return $this->belongsTo('App\Villa','unique_id', 'unique_id');
    }

    public function project()
    {
        return $this->belongsTo('App\Project','unique_id', 'unique_id');
    }

    public function farm_type()
    {
        return $this->belongsTo('App\FarmType');
    }

    public function farm_subject()
    {
        return $this->belongsTo('App\FarmSubject');
    }

}

app/ListingImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ListingImage extends Model
{
    //
}

app/ListingType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ListingType extends Model
{
    //
}

app/Presentation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Presentation extends Model
{
    //
}

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    public function province()
    {
        return $this->belongsTo('App\Province');
    }

    public function district()
    {
        return $this->belongsTo('App\District');
    }

    public function heating_type()
    {
        return $this->hasOne('App\HeatingType', 'id','heating_type_id');
    }

    public function deed_type()
    {
        return $this->belongsTo('App\DeedType');
    }

    public function swimming_pool()
    {
        return $this->belongsTo('App\SwimmingPool');
    }
}

app/Province.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Province extends Model
{
    public function district()
    {
        return $this->hasMany('App\District');
    }
}

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{


}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Villa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Villa extends Model
{
    public function province()
    {
        return $this->belongsTo('App\Province');
    }

    public function district()
    {
        return $this->belongsTo('App\District');
    }

    public function heating_type()
    {
        return $this->hasOne('App\HeatingType', 'id','heating_type_id');
    }

    public function deed_type()
    {
        return $this->belongsTo('App\DeedType');
    }

    public function swimming_pool()
    {
        return $this->belongsTo('App\SwimmingPool');
    }
}

app/Zoning.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Zoning extends Model
{
    //
}

resources/views/adminhome.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"></div>

                    <div class="panel-body">
                        <h4>{{ __ ('En çok görüntülenen ilanlar') }}</h4>

                        <div class="col-sm-12">
                            <table class="table table-striped table-bordered table-responsive table-condensed">

                                <thead>
                                <tr>
                                    <th>{{ __('İlan Başlığı') }}</th>
                                    <th>{{ __('İlan Numarası') }}</th>
                                    <th>{{ __('Emlak Tipi') }}</th>
                                    <th>{{ __('Konum') }}</th>
                                    <th>{{ __('Fiyat') }}</th>
                                    <th>{{ __('İncelenme Sayısı') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($listings as $listing)
                                    <tr>
                                        <td> {{ $listing->title }} </td>
                                        <td> {{ $listing->unique_id  }} </td>
                                        <td> {{ $listing->property_type->name }} </td>
                                        <td> {{ $listing->province->name . ' - ' . $listing->district->name }} </td>
                                        <td> {{ $listing->price . ' ' . $listing->currency->symbol }} </td>
                                        <td> {{ $listing->watch_count }} </td>
                                    </tr>
                                @endforeach
                                </tbody>

                            </table>
                        </div>


                    </div>
                    <div class="panel-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/front/estates.blade.php
@extends('front.layouts.front2')

@section('content')

    @include('front.partials.searched_estates')
    @include('front.footer')

@endsection

resources/views/front/farms.blade.php
@extends('front.layouts.front2')

@section('content')

    @include('front.partials.farm_listings')

    @include('front.footer')
@endsection

resources/views/front/flats.blade.php
@extends('front.layouts.front2')

@section('content')



    @include('front.partials.flat_listings')
    @include('front.footer')

@endsection

resources/views/front/footer.blade.php
<!-- START: footer -->
<footer role="contentinfo" class="probootstrap-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="probootstrap-footer-widget">
                    <h3>Karma GMG Hakkında</h3>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.
                        It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <p><a href="#" class="link-with-icon">Learn More <i class=" icon-chevron-right"></i></a></p>
                </div>
                <div class="probootstrap-footer-widget">
                    <h3>Connect With Us</h3>
                    <ul class="probootstrap-footer-social">
                        <li><a href=""><i class="icon-twitter"></i></a></li>
                        <li><a href=""><i class="icon-facebook"></i></a></li>
                        <li><a href=""><i class="icon-instagram2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="probootstrap-footer-widget">
                    <h3>{{ __('Popular Estates') }}</h3>
                    <ul class="probootstrap-product-list">
                        <li class="mb20">
                            <a href="#">
                                <figure><img src="img/img_3.jpg" alt="Free Bootstrap Template by uicookies.com"
                                             class="img-responsive"></figure>
                                <div class="text">
                                    <h4>River named Duden flows</h4>
                                    <p>A small river named Duden flows by their place</p>
                                    <p class="secondary-color rate"><i class="icon-star-full"></i><i
                                                class="icon-star-full"></i><i class="icon-star-full"></i><i
                                                class="icon-star-full"></i><i class="icon-star-half"></i></p>
                                </div>
                            </a>
                        </li>
                        <li class="mb20">
                            <a href="#">
                                <figure><img src="img/img_4.jpg" alt="Free Bootstrap Template by uicookies.com"
                                             class="img-responsive"></figure>
                                <div class="text">
                                    <h4>River named Duden flows</h4>
                                    <p>A small river named Duden flows by their place</p>
                                    <p class="secondary-color rate"><i class="icon-star-full"></i><i
                                                class="icon-star-full"></i><i class="icon-star-full"></i><i
                                                class="icon-star-full"></i><i class="icon-star-half"></i></p>
                                </div>
                            </a>
                        </li>
                        <li class="mb20">
                            <a href="#">
                                <figure><img src="img/img_5.jpg" alt="Free Bootstrap Template by uicookies.com"
                                             class="img-responsive"></figure>
                                <div class="text">
                                    <h4>River named Duden flows</h4>
                                    <p>A small river named Duden flows by their place</p>
                                    <p class="secondary-color rate"><i class="icon-star-full"></i><i
                                                class="icon-star-full"></i><i class="icon-star-full"></i><i
                                                class="icon-star-full"></i><i class="icon-star-half"></i></p>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="probootstrap-footer-widget">
                    <h3>{{ __('Recent Estates') }}</h3>
                    <ul class="probootstrap-blog-list">
                        @foreach($recent_listings as $recent_listing)

                            <li>
                                <a href="details/{{$recent_listing->unique_id}}">
                                    <figure><img src="images/{{$recent_listing->images[0]->resized_name}}"
                                                 class="img-responsive"></figure>
                                    <div class="text">
                                        <h4>{{ $recent_listing->title }}</h4>
                                        <p>{{ $recent_listing->price }} {{ $recent_listing->currency->symbol }}</p>
                                    </div>
                                </a>
                            </li>

                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
        <div class="row mt40">
            <div class="col-md-12 text-center">
                <p>
                    <small>&copy; {{ date("Y") }}<br> <a href="https://www.karmagmg.com/" target="_blank">{{ __('All Rights Reserved') }}</a>. <br>
                        <a href="#" class="js-backtotop">{{ __('Return to Top') }}</a>
                </p>
            </div>
        </div>
    </div>
</footer>

resources/views/front/home.blade.php
@extends('front.layouts.front2')

@section('content')
    <!-- START: section -->
    <section class="probootstrap-section">

        <div id="carousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                @foreach($slider_images as $key=>$simage)
                    <div class="carousel-item @if($key == 0) active @endif">
                        <img class="d-block w-100 img-responsive" src="img/slider/{{ $simage->filename }}">
                    </div>
                @endforeach
            </div>
        </div>

        <div id="search" class="search">
            <form action="{{ route('searchwith') }}" method="post">

            <select name="property_type" id="property_type">
                @foreach($property_types as $pt)
                <option value="{{ $pt->id }}">{{ __($pt->name) }}</option>
                @endforeach
            </select>
                {{ csrf_field() }}
                <input class="search-box" name="search_query"/>
                <button class="search-button">
                    <i class="fas fa-search"></i> {{ __('Search') }}
                </button>
            </form>
        </div>

    </section>

    @include('front.partials.all_listings')

    <!-- START: footer -->
    @include('front.footer')

    <script>
        let word = 'naber';
        let inputs = [];
        document.onkeypress = function (e) {
            e = e || window.event;
            let mWord = '';
            inputs.push(String.fromCharCode(e.keyCode));
            if (inputs.length == word.length) {
                for (i = 0; i < inputs.length; i++) {
                    mWord = mWord + inputs[i];
                }
            }
            if (mWord == word) {
                window.location.href = '/adminhome';
            }
        };
    </script>

    <script>
        $('.carousel').carousel({
            interval: 5000,
            pause: false
        })
    </script>
@endsection

resources/views/front/lands.blade.php
@extends('front.layouts.front2')

@section('content')

    @include('front.partials.land_listings')

    @include('front.footer')
@endsection

resources/views/front/lands_rff.blade.php
@extends('front.layouts.front2')

@section('content')

    @include('front.partials.land_listings')

    @include('front.footer')
@endsection

resources/views/front/listing_detail.blade.php
@extends('front.layouts.front2')

@section('content')
    <section class="probootstrap-section">
        <div class="container">
            <div class="col-md-6 col-md-push-6">
                <h2>{{ $listing->title }}</h2>
                <h3>
                    {{ number_format($listing->price,null,null,'.') }} {{ $listing->currency->symbol }}
                    <p class="pull-right">
                        <a>
                            <small>{{$listing->district->name}} / <strong>{{$listing->province->name}}</strong>
                                <i class="fas fa-map-marker-alt"></i>
                            </small>
                        </a>
                    </p>
                </h3>


                <table class="table table-condensed table-striped probootstrap-black-color">
                    <thead>
                    <tr>
                        <td colspan="4"><h4 class="text-danger pull-right"><strong>Teknik Ayrıntılar</strong></h4></td>
                    </tr>
                    </thead>
                    <tbody>

                    @include('front.partials.pt_'. $listing->property_type->id . '_detail')

                    </tbody>
                    @if($listing->precedent_value > 0)
                        <tfoot>
                        <tr>
                            <td><img class="micon" src="{{ asset('svg/skyscraper.svg') }}"/> Emsal Değeri</td>
                            <td colspan="3">{{ number_format($listing->precedent_value,null,null,'.') }} {{$listing->currency->symbol}}</td>
                        </tr>
                        </tfoot>
                    @endif
                </table>
                @if($listing->details != '')
                    <table class="table table-condensed table-striped probootstrap-black-color">
                        <thead>
                        <tr>
                            <td><h4 class="text-danger pull-right"><strong>Detaylar</strong></h4>
                            </td>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                {{ $listing->details }}

                            </td>
                        </tr>
                        </tbody>
                    </table>

                @endif
                @if($listing->presentation != null)

                    <p>
                        <a href="{{ route('download_presentation', $listing->unique_id) }}" role="button"
                           class="btn btn-primary">Sunumu İndir</a>
                    </p>

                @endif
            </div>

            <div class="col-md-6 col-md-pull-6">
                <div class="im" style="margin-top: 4em">
                    @foreach($listing->images as $image)
                        <a href="/images/{{ $image->resized_name }}" class="image-popup">
                            <img src="/images/{{ $image->resized_name }}" alt="" class="img-responsive">
                        </a>
                    @endforeach
                </div>

            </div>

        </div>
    </section>


@endsection

resources/views/front/partials/all_listings.blade.php
<section class="probootstrap-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 section-heading probootstrap-animate">
            </div>
        </div>
        <div class="row mb70">

            @include('front.partials.listings_as_columns')

        </div>
    </div>
</section>

resources/views/front/partials/pt_2_detail.blade.php
<tr>
    <td><img class="micon" src="/svg/034-area.svg" title=""/> Brüt Alan :</td>
    <td>{{ $listing->land->gross_area }} m<sup>2</sup></td>
    <td><img class="micon" src="/svg/034-area.svg" title=""/> Net Alan :</td>
    <td>{{ $listing->land->net_area }} m<sup>2</sup></td>
</tr>
<tr>
    <td><img class="micon" src="/svg/032-plan.svg" title=""/> Ada / Parsel:</td>
    <td>{{ $listing->land->block }} / {{ $listing->land->plot }}</td>
    <td></td>
    <td></td>

</tr>
<tr>
    <td><img class="micon" src="/svg/014-crane.svg" title=""/> İmar Durumu :</td>
    <td>{{ $listing->land->zoning->name }}</td>
    <td></td>
    <td></td>
</tr>

resources/views/front/partials/searched_estates.blade.php
<section class="probootstrap-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 section-heading probootstrap-animate">
            </div>
        </div>
        <div class="row mb70">
            @include('front.partials.listings_as_columns')


        </div>
    </div>
</section>

resources/views/front/projects.blade.php
@extends('front.layouts.front2')

@section('content')


    @include('front.partials.project_listings')
    @include('front.footer')

@endsection

resources/views/front/villas.blade.php
@extends('front.layouts.front2')

@section('content')


    @include('front.partials.villa_listings')
    @include('front.footer')

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>

<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>


    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Karma GMG') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
    {{--<link href="{{ asset('css/fontawesome.css') }}" rel="stylesheet">--}}
    <link href="{{ url('https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css') }}"
          rel="stylesheet">

    <!-- JS -->
    <script src="{{ url('https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js') }}"></script>
    <script src="{{ url('https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js') }}"></script>
    <script src="{{ asset('js/dropzone.js') }}"></script>

    {{-- <script src="{{ asset('js/fontawesome.js') }}"></script>--}}
    <script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"
            integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0"
            crossorigin="anonymous"></script>

</head>
<body>
<div id="app">

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding ListingImage -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Karma GMG') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->

                @if (Auth::guest())
                    <!--
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        -->
                    @else
                       <li> <a href="{{ route('listings.index') }}">
                            <i class="fas fa-list"></i> İlanlar
                        </a></li>

                        <li class="dropdown">



                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>

                                    <a href="{{ route('techsupport.index') }}">
                                        <i class="fas fa-question-circle"></i> Yardım
                                    </a>

                                    <a href="{{ route('settings')}}">
                                        <i class="fas fa-cog"></i><small> Ayarlar (Deaktif)
                                        </small>
                                    </a>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <i class="fas fa-sign-out-alt"></i> Çıkış
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')
</div>

<script>

    let loading = false;

    function showLoading() {
        if (!loading) {
            html = '<div id="loading">' +
                '<h4 style="color:white">' +
                'Lütfen Bekleyin ' +
                '<img src="{{ asset('img/loader.gif') }}" id="loadingImage">' +
                '</h4>' +
                '</div>'
            $('#app').append(html);
            loading = true
        }
    }

    function hideLoading() {
        if (loading) {
            $('#loading').remove();
            loading = false
        }
    }

</script>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
<script>
    // Note: This example requires that you consent to location sharing when
    // prompted by your browser. If you see the error "The Geolocation service
    // failed.", it means you probably did not give permission for the browser to
    // locate you.
    var map, infoWindow;

    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: -34.397, lng: 150.644},
            zoom: 6
        });
        infoWindow = new google.maps.InfoWindow;

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                infoWindow.setPosition(pos);
                infoWindow.setContent('Location found.');
                infoWindow.open(map);
                map.setCenter(pos);
            }, function () {
                handleLocationError(true, infoWindow, map.getCenter());
            });
        } else {
            // Browser doesn't support Geolocation
            handleLocationError(false, infoWindow, map.getCenter());
        }
    }

    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
            'Error: The Geolocation service failed.' :
            'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
    }
</script>

<!--
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAiqQk7xmL8ulSlppgXne9YwNDhTdkJ0_Q&callback=initMap">
</script>

-->
</body>
</html>